name: geca
description: GECA is an integrated platform for students to provide most of the materials they need during their educational journey in a well-organized way. What can you get on GECA? Easy access to the official website of Government Engineering College, Ajmer. Get stream-wise courses containing well-organized video lectures and supporting materials. Access to e-notes and e-Books. Access to archives full of documents contributed by volunteers. Articles suggested by professionals related to research, innovation, business, etc. Easy access to National Digital Library of India. Access to Reference Bank full of references to various helpful sources. GECA app is build to save the time of students. It helps to minimize their effort in search of better resources for quality education. We hope you'll feel better and enjoy using GECA as much as we enjoyed developing it. Looking forward to your participation in creating this platform more reliable for the education system. Easy access to official website. Get courses, notes and books. Read articles.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
  sdk: ">=2.17.3 <3.0.0"

# dependencies:
#   flutter:
#     sdk: flutter
#   firebase_core: ^1.3.0
#   cloud_firestore: ^2.3.0
#   firebase_storage: ^8.1.3
#   google_mobile_ads: ^0.13.0
#   webview_flutter: ^2.0.10
#   flutter_inappwebview: ^5.3.2
#   connectivity: ^3.0.6
#   url_launcher: ^6.0.4
#   provider: ^5.0.0
#   package_info: ^2.0.2
#   share_plus: ^2.1.2
#   cached_network_image: ^3.0.0
#   permission_handler: ^8.0.0+2
#   shared_preferences: ^2.0.6

dependencies:
  flutter:
    sdk: flutter
  #  platform: ^3.1.0
  firebase_core: ^2.13.0
  cloud_firestore: ^4.7.1
  # cloud_firestore: ^3.1.10
  firebase_storage: ^11.2.1
  firebase_auth: ^4.6.1
  google_mobile_ads: ^2.4.0
  webview_flutter: ^3.0.4
  connectivity: ^3.0.6
  provider: ^6.0.2
  package_info: ^2.0.2
  share_plus: ^2.1.2
  cached_network_image: ^3.2.1
  permission_handler: ^10.2.0
  shared_preferences: ^2.0.6
  flutter_downloader: ^1.7.2
  intl: ^0.17.0
  file_picker: ^5.3.0
  device_info_plus: ^9.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Flutter Icon and Splash is not working at once use one by one
  # flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.2.0

# flutter_icons:
#   # flutter pub run flutter_launcher_icons:main
#   android: true
#   # ios: true
#   image_path: "assets/GECA.png"
#   adaptive_icon_background: "#FFFFFF"
#   #240E7B
#   adaptive_icon_foreground: "assets/GECA-A.png"

flutter_native_splash:
  # flutter pub run flutter_native_splash:create

  color: "#ffffff"
  #background_image: "assets/background.png"
  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file.
  image: assets/GECA.png

  android: true
  ios: false
  web: false
  android_gravity: center
  fullscreen: false

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fileImage.png
    - assets/3.webp
    - assets/not_found.png
    - assets/gecaLogo.png
    - assets/comingSoonLogo.jpg
    - assets/facebook.jpg
    - assets/twitter.jpg
    - assets/email.png
    - assets/linkedin.png
    - assets/koo.png
    - assets/whatsapp.png
    - assets/NDL.png
    - assets/NDLLogo.png
    - assets/reference.png
    - assets/icon.png
    - assets/GECA.png
    - assets/logo.png
    - assets/logo-dark.png
    - assets/logo-light.png
    - assets/GeneralTexture/image1.jpg
    - assets/GeneralTexture/image2.jpg
    - assets/GeneralTexture/image3.jpg
    - assets/GeneralTexture/image4.jpg
    - assets/GeneralTexture/image7.jpg
    - assets/GeneralTexture/image19.jpg
    - assets/GeneralTexture/image23.jpg
    - assets/GeneralTexture/image221.jpeg
    - assets/GeneralTexture/image111.jpg
    - assets/LeatherTexture/L11.jpg
    - assets/LeatherTexture/L43.jpg
    - assets/LeatherTexture/L53.jpg
    - assets/LeatherTexture/L73.jpg
    - assets/LeatherTexture/L103.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Signika
      fonts:
        - asset: fonts/Signika-Bold.ttf
          weight: 700
        - asset: fonts/Signika-Light.ttf
          weight: 300
        - asset: fonts/Signika-Medium.ttf
          weight: 500
        - asset: fonts/Signika-Regular.ttf
          weight: 400
        - asset: fonts/Signika-SemiBold.ttf
          weight: 600
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
